# Generated by Django 4.1.6 on 2023-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighLightLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(max_length=15, null=True)),
                ('highlightlink', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('himg', models.CharField(max_length=100, null=True)),
                ('aimg', models.CharField(max_length=100, null=True)),
                ('teams', models.CharField(max_length=50, null=True)),
                ('hteam', models.CharField(max_length=50, null=True)),
                ('ateam', models.CharField(max_length=50, null=True)),
                ('link', models.ManyToManyField(to='highlights.highlightlink')),
            ],
        ),
    ]
