# Generated by Django 4.1.6 on 2023-02-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='time',
        ),
        migrations.AddField(
            model_name='highlight',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='highlight',
            name='result',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
