# Generated by Django 4.1.6 on 2023-02-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_premium_alter_news_body_alter_news_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='premium',
        ),
    ]
