# Generated by Django 4.1.6 on 2023-02-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('messenger', models.CharField(max_length=10)),
            ],
        ),
    ]
