# Generated by Django 4.1.6 on 2023-02-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('messenger', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TextAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('show', models.BooleanField()),
                ('link', models.CharField(max_length=100)),
                ('messenger', models.CharField(max_length=10)),
            ],
        ),
    ]
