# Generated by Django 4.1.6 on 2023-02-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='ateam',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='hotmat',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='hteam',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='league',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='teams',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livelinks',
            name='video_type',
            field=models.CharField(default='', max_length=15),
        ),
    ]
