# Generated by Django 4.1.6 on 2023-02-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_live_ateam_live_hotmat_live_hteam_live_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='aimg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='himg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='livelinks',
            name='livelink',
            field=models.TextField(null=True),
        ),
    ]
