# Generated by Django 4.1.6 on 2023-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_live_aimg_live_himg_livelinks_livelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='aimg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='live',
            name='himg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livelinks',
            name='livelink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livelinks',
            name='video_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
