# Generated by Django 4.1.6 on 2023-02-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_live_link_livelinks_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livelinks',
            name='live',
        ),
        migrations.AddField(
            model_name='live',
            name='link',
            field=models.ManyToManyField(to='myapp.livelinks'),
        ),
    ]
