# Generated by Django 4.1.6 on 2023-02-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_livelinks_live_live_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='live',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
