# Generated by Django 4.1.6 on 2023-02-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_live_premium_live_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='link',
            field=models.ManyToManyField(null=True, to='myapp.livelinks'),
        ),
    ]
