# Generated by Django 4.1.6 on 2023-02-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_live_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='link',
            field=models.ManyToManyField(blank=True, to='myapp.livelinks'),
        ),
    ]
