# Generated by Django 4.1.6 on 2023-02-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField()),
                ('downloadLink', models.CharField(max_length=15, null=True)),
                ('playLink', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100, null=True)),
                ('sname', models.CharField(max_length=50, null=True)),
                ('link', models.ManyToManyField(to='series.part')),
            ],
        ),
    ]
