# Generated by Django 4.1.6 on 2023-02-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_desc_alter_part_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
