# Generated by Django 4.1.6 on 2023-02-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('link', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='playLink',
        ),
        migrations.AddField(
            model_name='movie',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='downloadLink',
        ),
        migrations.AddField(
            model_name='movie',
            name='downloadLink',
            field=models.ManyToManyField(null=True, to='movies.link'),
        ),
    ]
