# Generated by Django 4.1.6 on 2023-02-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_link_remove_movie_playlink_movie_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='downloadLink',
            field=models.ManyToManyField(to='movies.link'),
        ),
    ]
